--TEST1
SELECT STUDENT_NO,STUDENT_NAME, TO_CHAR(ENTRANCE_DATE, 'YYYY"/"MM"/"DD'),D.DEPARTMENT_NAME
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND D.DEPARTMENT_NAME = '영어영문학과'
ORDER BY STUDENT_NAME;

--TEST2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--TEST3
SELECT PROFESSOR_NAME,

CASE
WHEN 
TO_CHAR(SYSDATE, 'MMDD') > SUBSTR(PROFESSOR_SSN, 3,4)
THEN
(TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900))+1

WHEN
TO_CHAR(SYSDATE, 'MMDD') < SUBSTR(PROFESSOR_SSN, 3,4)
THEN
TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900)

END "나이"


FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1;

--TEST4
SELECT SUBSTR(PROFESSOR_NAME,2,2)
FROM TB_PROFESSOR;

--TEST5
SELECT STUDENT_NO, STUDENT_NAME,(EXTRACT(YEAR FROM STUDENT_SSN)) -( EXTRACT(YEAR FROM ENTRANCE_DATE))
FROM TB_STUDENT;
--ENTRANCE_DATE 입학년도랑 STUDENT_SSN 주민번호 비교하기

