--TEST1
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

--TEST2
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY ||'명입니다'
FROM TB_DEPARTMENT;

--TEST3
SELECT STUDENT_NAME
FROM TB_STUDENT, TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과' AND STUDENT_SSN LIKE '_______2%' AND ABSENCE_YN = 'Y' ;

--TEST4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079' ,'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

--TEST5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--TEST6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--TEST7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--TEST8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--TEST9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--TEST10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND STUDENT_NO LIKE 'A2%' AND ABSENCE_YN = 'N';