 --TEST1
 SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
 FROM TB_STUDENT
 ORDER BY 1;
 
 --TEST2
 SELECT STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY 2 DESC;
 
 --TEST3
 SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
 FROM TB_STUDENT
 WHERE STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '경기도%'
 AND SUBSTR(STUDENT_NO,1,1)= '9'
 ORDER BY 1;
 
 --TEST4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2;

--TEST5 / 소수점 추가 방법 모르겠음
SELECT STUDENT_NO, ROUND(POINT,2)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE TERM_NO = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC;

--TEST6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2; 

--TEST7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--TEST8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C , TB_PROFESSOR P
WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO
ORDER BY 2 ;

--TEST9
SELECT S.STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
WHERE S.STUDENT_NO = G.STUDENT_NO
AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO, STUDENT_NAME
ORDER BY 1;

--TEST10 담당지도교수 이름 안나옴
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 교수이름
FROM TB_DEPARTMENT D, TB_STUDENT S, TB_PROFESSOR P
WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO
AND D.DEPARTMENT_NO = P.DEPARTMENT_NO
AND STUDENT_NO = 'A313047'
AND PROFESSOR_NO
=(SELECT COACH_PROFESSOR_NO FROM TB_STUDENT WHERE STUDENT_NO = 'A313047');
--AND COACH_PROFESSOR_NO = 
--(SELECT COACH_PROFESSOR_NO FROM TB_STUDENT
--WHERE STUDENT_NO = 'A313047' );


--TEST11 학생수가 여러명 나옴
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D, TB_CLASS C
WHERE S.STUDENT_NO = G.STUDENT_NO
AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND D.DEPARTMENT_NO = C.DEPARTMENT_NO
AND SUBSTR(TERM_NO,1, 4) = '2007'
AND CLASS_NAME = '인간관계론';


--TEST12 담당교수 한명도 배정받지못한 학과
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C , TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND CATEGORY = '예체능';

--TEST13 이건모르겠음
SELECT STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.DEPARTMENT_NO = P.DEPARTMENT_NO
AND DEPARTMENT_NAME  = 
(SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '서반아어학과');


SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '서반아어학과';

--TEST14
SELECT S.STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME 학과이름, ROUND(AVG(G.POINT),1) 평점
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_GRADE G
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
AND ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(G.POINT) >= 4.0
ORDER BY 1;

--TEST15
SELECT C.CLASS_NO, CLASS_NAME, ROUND(AVG(POINT),1)
FROM TB_CLASS C, TB_GRADE G, TB_DEPARTMENT D
WHERE C.CLASS_NO = G.CLASS_NO
AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
GROUP BY C.CLASS_NO, CLASS_NAME, DEPARTMENT_NAME, CLASS_TYPE
HAVING  DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
ORDER BY 1;

--TEST16
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT S , TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND STUDENT_ADDRESS IS NOT NULL
AND DEPARTMENT_NAME =
(SELECT DEPARTMENT_NAME
FROM  TB_STUDENT S , TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO 
AND STUDENT_NAME = '최경희');

--TEST17
SELECT S.STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT S , TB_GRADE G, TB_DEPARTMENT D
WHERE S.STUDENT_NO = G.STUDENT_NO
AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) =
(SELECT MAX(AVG(POINT))
FROM TB_GRADE G, TB_DEPARTMENT D, TB_STUDENT S
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
GROUP BY STUDENT_NAME, DEPARTMENT_NAME
HAVING DEPARTMENT_NAME = '국어국문학과');

--TEST18
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT D, TB_GRADE G, TB_STUDENT S
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
GROUP BY DEPARTMENT_NAME, CATEGORY
HAVING CATEGORY = 
(SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT WHERE CATEGORY = '자연과학');