--TEST1
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, RANK
FROM
         (SELECT
        RANK() OVER(ORDER BY ((SALARY*NVL(BONUS,0))+SALARY)*12 DESC) "RANK",
        EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
         FROM EMPLOYEE E , DEPARTMENT D, JOB J
         WHERE E.DEPT_CODE = D.DEPT_ID
         AND E.JOB_CODE = J.JOB_CODE
         )
WHERE RANK <=5;

--TEST2
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > ALL(SELECT SUM(SALARY)*0.2
                            FROM EMPLOYEE);

--TEST3
WITH EMP_SALARY
AS(SELECT SUM(SALARY) SUM, AVG(SALARY) AVG
FROM EMPLOYEE)
SELECT SUM, AVG
FROM EMP_SALARY;

  